### PR TITLE
Fixed CrashLoopBackOff and implemented PR comments from Kuberetes

### PR DESCRIPTION
**Pull request by jonhoare**
Hi @jpoon.

I was following your [PR](https://github.com/kubernetes/charts/pull/766) for your mysqlha charts, which were really helpful for me.

I have managed to get these charts now working locally fixing up the issues that was causing the 2nd container to crash.

I have also refactored to use the new "initContainers" specification as this is now out of beta, and have taken on board some of the comments from the PR for you, such as moving some of the files out and referencing them via Files.Get, removing the hard-coded "default" storageClass as this not required, and made the full images for mysql and xtrabackup variable.

I thought I would send you a PR with my changes as you had done almost all the work on this and deserve the credit should you PR this again with kubernetes.

Let me know what you think.

### CODE REVIEW

**Comment by jpoon** [comment]
Woohoo! Thanks so much @jonhoare! This has been on my to-list for such a long time. I'll test this out when I'm back in front of my computer, and we can re-submit this back to the Helm charts repo.

**Comment by jonhoare** [comment]
That would be awesome thanks. 

I had found your PR while I was looking at the kubernetes mysqlha tutorial and went looking to see if there was a helm chart I could use, so was following intently to save me trying to figure out how to do it myself as I was completely new to using helm. 

So when I saw you were having issues and running out of time I thought it would be a good chance for me to try and dive into the templates and see if I could learn and fix it up to work for my purposes. Turns out to have a been a good first attempt for me 😃.

There's still a couple of things that I wanted to do...

1. Move the main 2 containers into separate images to be referenced using Files.Get like I did with the initContainers. But when I did try late last night, I only managed to move the mysql container successfully, and when I tried to do the same with xtrabackup, I couldn't get the pods to come up. So I did give up with moving the 2 containers.

2. I also read that the storageClass has moved from being an annotation to being implemented using [storageClassName](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1) which does still work but will be obsoleted in the future, so this will need changing. However, again when I tried to change this, I couldn't get the Persistent Volumes and Claims to come up successfully.

Maybe I will get a chance to look at those and send you a new PR if I can get them working, but at the moment I had it working.

**Comment by jpoon** [comment]
Re-opened the PR against the `charts` repo. You'll need to sign the Linux Foundation CLA.

**Comment by jonhoare** [comment]
Cool thanks. I've just signed it now

**Comment by jonhoare** [comment]
Hey @jpoon, I'm having a little issue myself locally, which I don't know if it's just my setup and wondered if it is something you have seen before.

My deployment comes up with all the pods. `mysqlha-mysqlha-0`, `mysqlha-mysqlha-1`, `mysqlha-mysqlha-2`.

I can create a database against `mysqlha-mysqlha-0` and access/use this database perfectly fine when connecting directly to `mysqlha-mysqlha-0.mysqlha-mysqlha`. However if I connect to the mysql instance via the readonly service `mysqlha-mysqlha` or directly against `mysqlha-mysqlha-1.mysqlha-mysqlha` or `mysqlha-mysqlha-2.mysqlha-mysqlha`, I don't appear to be able to see the database that exists on `mysqlha-mysqlha-0`.

Have you seen this before? I think I'm now getting into the part of the process which I don't understand fully.

**Comment by jpoon** [comment]
Oh no, I didn't test that part of it in the latest revision. After a small delay, you should be seeing the same data across all the instances. Each instance is replicating from the index-1 so instance 2 replicates from instance 1 and instance 1 replicates from instance 0.

**Comment by jonhoare** [comment]
Hmmm that's what I figured, but mine are definitely not replicating properly. I must have broken something, hopefully its not a problem with the templates and only with my deployment. Would you be able to run it up and give it a quick check to see if it works for you?

**Comment by jpoon** [comment]
Hmm, the `.Files.Get` don't seem to be working. The initContainers is empty:

```
   spec:
      initContainers:


      containers:
      - name: mysql
```

Trying to figure out how to resolve this....

**Pull request merged**
